### ISSUE TITLE
Feedback on 'Creating a new data broker in AWS'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-copy-sync#49]
Page: [Creating a new data broker in AWS](https://docs.netapp.com/us-en/cloud-manager-sync/task-installing-aws.html)
The following feedback was sent to ng-doccomments:

https://s3.amazonaws.com/metadata.datafabric.io/docs/aws_iam_policy.json
This no longer contains all the required permissions and is missing kms:ListAliases
The json needs to be updated.

**Comment by netapp-tonacki** [comment]
I see the permission that they said is missing:
![image](https://github.com/NetAppDocs/bluexp-copy-sync/assets/38222299/5a524964-260c-4350-ad35-a2c76e9bd283)
