### ISSUE TITLE
Request for example for Proxy configuration with "domain username" (format) on multiple pages

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/bluexp-copy-sync#55]
Page: [Configure a Connector to use a proxy server](https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-configuring-proxy.html)

Request for example for Proxy configuration with "domain username" (format) on multiple pages below:

1. Connector UI:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-configuring-proxy.html#enable-a-proxy-on-a-connector

2. Connector manual install on linux host:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-on-prem.html#install-the-connector

3. Connector pre-requites mention:
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-set-up-networking-on-prem.html#endpoints-contacted-from-the-connector

4. Data Sense manual install:
https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#single-host-installation-for-typical-configurations

5. Data Broker manual install:
https://docs.netapp.com/us-en/cloud-manager-sync/task-installing-linux.html#installing-the-data-broker

**Comment by netapp-tonacki** [comment]
@netapp-ivanad, please see 5 above. Ben handled #1-3. I handled number 4 for the Classification docs.

Please close the issue when you're done.

**Comment by netapp-ivanad** [comment]
Domain usernames are also not supported for data brokers. The docs have been updated to reflect this.
