### ISSUE TITLE
Update Cloud Data Sense name

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-copy-sync#59]
### Page URL

https://docs.netapp.com/us-en/bluexp-copy-sync/reference-networking.html

### Page title

Networking overview for BlueXP copy and sync

### Summary

"Cloud Data Sense" should be "BlueXP classification"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ivanad** [comment]
Thank you for bringing this to our attention! The repo has been updated with the changes.
