### ISSUE TITLE
docs_feedback: https://docs.netapp.com/us-en/bluexp-copy-sync/faq.html

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-copy-sync#64]
### Summary

 https://docs.netapp.com/us-en/bluexp-copy-sync/faq.html#what-happens-if-i-delete-something-from-my-source-server-is-it-removed-from-the-target-too

Does data broker have any limitations like file name/path length etc. when syncing?
Or depend on source and target storage limitation?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ivanad** [comment]
Hello! Thank you for submitting this question.

Yes, limitations on file name and path are dependent on the target storage limitation. For example, Linux machines have a limitation of 255 for paths.
