### ISSUE TITLE
Feedback on Supported sync relationships

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/bluexp-copy-sync#66]
### Summary

This page shows `Box support is available as a preview.`

Has it still been in the preview phase even though two years have passed since the initial release?

According to the release notes of October 31 2021,
I understand that the Box Copy and Sync UI is in preview. However, is this feature not officially released yet?

The release notes show as follows

2 January 2022
New Box sync relationships
Two new sync relationships are supported:
•	Box to Azure NetApp Files
•	Box to Amazon FSx for ONTAP

31 October 2021
Box support
Box support is now available in the Cloud Sync user interface as a preview.
Box can be the source or target in several types of sync relationships. [View the list of supported sync relationships](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fbluexp-copy-sync%2Freference-supported-relationships.html&data=05%7C01%7CChanda.Jha%40netapp.com%7Ca976c77a7e414a94b02d08dbe1afb588%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638351917023825445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LItAC0TaNgqvkRkKos%2BQlA0BTOpSi9OUJWeg95kM%2BU4%3D&reserved=0).
4 October 2021
Additional Box support
Cloud Sync now supports additional sync relationships for [Box](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.box.com%2Fhome&data=05%7C01%7CChanda.Jha%40netapp.com%7Ca976c77a7e414a94b02d08dbe1afb588%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638351917023825445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=v7a8C1x1zE5A43uAqRUFGwSxQEA6Fw2Sf8bMkYsSf0g%3D&reserved=0) when using the Cloud Sync API:

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ivanad** [comment]
Hi @netapp-chandaj, thank you for your question. I'll work on getting this addressed!

**Comment by netapp-ivanad** [comment]
Thank you for submitting this feedback! Currently, the status for this feature has not changed since its initial release and there are no updates that can be made to the product documentation. If any updates do occur, the "What's new" page for this product will be updated.
