### ISSUE TITLE
Update what protocols are supported under "On-premises ONTAP cluster"

### ISSUE THREAD

**Issue by jasonfiset** [NetAppDocs/bluexp-copy-sync#74]
### Page URL

https://docs.netapp.com/us-en/bluexp-copy-sync/reference-supported-relationships.html

### Page title

Supported sync relationships

### Summary

The description "On-premises ONTAP cluster" could be interpreted to mean NFS/CIFS and S3 protocols which are all protocols run by ONTAP.  In the Azure Blob relationship in particular it's not clear if ONTAP S3 is included in this description or not.  Looking at Amazon S3 and noticed it specifically listed ONTAP S3 as a separate line item.  Would it be possible to update "On-premises ONTAP cluster" throughout this page to say "On-premises ONTAP cluster (NFS/CIFS)" throughout this page just so there is no further confusion on which specific protocols are supported? 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@jasonfiset, thank you for submitting this feedback. I updated the text to "On-premises ONTAP cluster (NFS or SMB)"

Thanks again,
Ben
