### ISSUE TITLE
Improperly numbered steps and incorrect capitalization of product name

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/bluexp-copy-sync#77]
### Page URL

https://docs.netapp.com/us-en/bluexp-copy-sync/api-sync.html

### Page title

BlueXP copy and sync APIs

### Summary

In the Getting Started section on this page, there are two #1 steps. 

There is also an instance of the product name incorrectly capitalized as "BlueXp" (note the lowercase p.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Adam,

Thank you for providing this feedback. I fixed the numbering issue and incorrect capitalization.
